# What is machine learning?

#### Machine learning is a method of data analysis that automates analytical model building. It is a branch of artificial intelligence based on the idea that systems can learn from data, identify patterns and make decisions with minimal human intervention.

In [ ]:
cambridge analytics, alpha go, investment banks, poker, marketing, spotify

 basic set up

 1) Get data - What data do you need to predict something?

2) Data exploration - gain understanding (are there biases)

3) Manipulate data - (missing data, type (nominal, ordinal, continuous, binary etc..), which variables to use, can you make more informative data (most cases no, but some like distance from postcodes))

4) What result do you want? - high weighted recall or high macro precision

5) What model works best and what parameterisation would work?

6) Test out different models

7) What other data can you get to improve model

8) Is there bias to the data

 we will use sickit learn

 example 1) poker
 
 example 2) face detection
 
 example 3) credit card purchases

## main types of ml

### type by output

##### classification 

 categorizes data

 e.g. weather, image, invest/not invest, tumor (binary)

##### regression
 
 continuous numeric values
 
 e.g. stock prices, temperature, amount of rain

 ##### clustering
 
 organize data into similar groups
 
 e.g. CV job type, customer segmentation,  stock types

 ##### association analysis
 
 capture associations between items or events
 
 e.g. market basket analysis, youtube/spotify prediction

 ### each of these can be further segmented into two

###### supervised 

target is provided, labelled

generally classification and regression fall into this bracket

#####  unsupervised 
  target is unknown, unlabelled
 
 generally clustering and association analysis are unsupervised
 
 in clustering you're grouping by similar characteristics

 semi-supervised learning is combination
 some labeled some unlabelled
 Used when there is a lot of data and labelling is timeconsuming

##### Other

 Reinforcement learning
 Pretty much what humans do

if you had a game each time you play it you get a score
you start off no idea what options to do: chess poker life
you try something you lose. You become less likely to do what you just tried
after 10 attempts you get a positive score, and whatever you did that time
you will be more likely to repeat.
This will iterate over and over

##### Common methods

Linear Regression - y = ax + b 

Logistic  - classification the dependent variable is dichotomous

Decision Tree - splits data into two sides
, works categorical or continuous

Random Forest - ensemble

SVM - n dimensional space, finds lines to split data


Naive Bayes (asssumes no correlation between features)

kNN - classification and regression, euclidean manhattan distances

Kernel approximation

K-Means - clustering

Dimensionality Reduction Algorithms - helps get rid of unimportant variables

Gradient Boosting algorithms: combination of weak predictors
- GBM
- XGBoost (gradient boosted trees, Pruning)

- LightGBM
- CatBoost
- SGD
- ADA-Boost

Deep learning

Ensembling: voting classifier

### THings to know

##### Sample: 
It is good practice to use a training set and test set

##### Data types:
Categorical

numerical - continuous, integers, dichotomous

Time/date

strings/ descriptions

##### You need to transform data determining on  method



What does it mean for prediction to be good?
accuracy vs precision vs recall  vs f1

2* p*r/(p+r)

As a summary, Scikit-learn provides an extensive
set of tools for the full Machine Learning process.
Thanks to Python we can combine these tools with
the rest of the data science tools in Python

In [37]:
from sklearn.metrics import classification_report

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, regression_data.applied, test_size=0.2)
model = xgb.XGBClassifier(max_depth=10, scale_pos_weight=3.4)
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

# Example 1

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>
Daily Weather Data Analysis</p>

In this notebook, we will use scikit-learn to perform a decision tree based classification of weather data.

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Importing the Necessary Libraries<br></p>

In [14]:
import pandas as pd
import xgboost as xgb
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Creating a Pandas DataFrame from a CSV file<br></p>

In [13]:
data = pd.read_csv('daily_weather.csv')

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold">Daily Weather Data Description</p>
<br>
The file **daily_weather.csv** is a comma-separated file that contains weather data.  This data comes from a weather station located in San Diego, California.  The weather station is equipped with sensors that capture weather-related measurements such as air temperature, air pressure, and relative humidity.  Data was collected for a period of three years, from September 2011 to September 2014, to ensure that sufficient data for different seasons and weather conditions is captured.<br><br>
Let's now check all the columns in the data.

In [15]:
data.columns

Index(['number', 'air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am',
       'relative_humidity_3pm'],
      dtype='object')

<br>Each row in daily_weather.csv captures weather data for a separate day.  <br><br>
Sensor measurements from the weather station were captured at one-minute intervals.  These measurements were then processed to generate values to describe daily weather. Since this dataset was created to classify low-humidity days vs. non-low-humidity days (that is, days with normal or high humidity), the variables included are weather measurements in the morning, with one measurement, namely relatively humidity, in the afternoon.  The idea is to use the morning weather values to predict whether the day will be low-humidity or not based on the afternoon measurement of relative humidity.

Each row, or sample, consists of the following variables:

* **number:** unique number for each row
* **air_pressure_9am:** air pressure averaged over a period from 8:55am to 9:04am (*Unit: hectopascals*)
* **air_temp_9am:** air temperature averaged over a period from 8:55am to 9:04am (*Unit: degrees Fahrenheit*)
* **air_wind_direction_9am:** wind direction averaged over a period from 8:55am to 9:04am (*Unit: degrees, with 0 means coming from the North, and increasing clockwise*)
* **air_wind_speed_9am:** wind speed averaged over a period from 8:55am to 9:04am (*Unit: miles per hour*)
* ** max_wind_direction_9am:** wind gust direction averaged over a period from 8:55am to 9:10am (*Unit: degrees, with 0 being North and increasing clockwise*)
* **max_wind_speed_9am:** wind gust speed averaged over a period from 8:55am to 9:04am (*Unit: miles per hour*)
* **rain_accumulation_9am:** amount of rain accumulated in the 24 hours prior to 9am (*Unit: millimeters*)
* **rain_duration_9am:** amount of time rain was recorded in the 24 hours prior to 9am (*Unit: seconds*)
* **relative_humidity_9am:** relative humidity averaged over a period from 8:55am to 9:04am (*Unit: percent*)
* **relative_humidity_3pm:** relative humidity averaged over a period from 2:55pm to 3:04pm (*Unit: percent *)

In [23]:
data.head(1000)

,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.000000,0.000000,42.420000,36.160000
1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.000000,0.000000,24.328697,19.426597
2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.000000,20.000000,8.900000,14.460000
3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.000000,0.000000,12.189102,12.742547
4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.900000,14730.000000,92.410000,76.740000
5,915.300000,78.404000,182.800000,9.932014,189.000000,10.983375,0.020000,170.000000,35.130000,33.930000
6,915.598868,70.043304,177.875407,3.745587,186.606696,4.589632,0.000000,0.000000,10.657422,21.385657
7,918.070000,51.710000,242.400000,2.527742,271.600000,3.646212,0.000000,0.000000,80.470000,74.920000
8,920.080000,80.582000,40.700000,4.518619,63.000000,5.883152,0.000000,0.000000,29.580000,24.030000
9,915.010000,47.498000,163.100000,4.943637,195.900000,6.576604,0.000000,0.000000,88.600000,68.050000
10,919.650000,77.036000,70.600000,3.825167,85.500000,4.764682,0.000000,0.000000,22.070000,32.130000
11,915.640000,45.716000,241.600000,5.860783,265.800000,8.030615,0.550000,1770.000000,90.560000,79.090000
12,917.390000,49.784000,204.100000,1.275056,211.800000,2.013246,0.000000,0.000000,73.150000,58.430000
13,920.820000,62.438000,213.600000,2.617220,165.700000,3.310671,0.000000,0.000000,43.640000,27.990000
14,911.000000,86.432000,202.900000,1.207948,162.900000,1.677705,0.000000,0.000000,15.190000,24.370000
15,922.383131,70.865263,36.174175,1.847278,58.428632,2.529142,0.000000,0.000000,12.110889,14.801706
17,916.915255,77.018961,234.539345,2.274725,229.474199,2.906513,0.000000,0.000000,21.031462,20.755683
18,918.800000,67.082000,176.100000,4.876529,183.400000,5.569981,0.000000,0.000000,18.900000,45.870000
19,922.040000,68.576000,58.300000,9.551734,81.900000,12.571603,0.000000,0.000000,7.540000,7.740000
20,919.992262,62.964383,54.799094,12.680436,74.254223,15.452306,0.000000,0.000000,18.809518,14.649909
21,917.230000,67.676000,177.800000,2.460634,93.200000,3.288302,0.000000,0.000000,40.640000,41.340000
22,921.125626,68.818772,71.799092,2.576538,95.472334,3.487444,0.000000,0.000000,11.742201,17.281161
23,920.350000,47.570000,192.100000,6.263432,205.700000,7.605596,0.000000,0.000000,54.550000,66.000000
24,921.788229,71.659572,217.405520,1.946447,253.758003,2.719712,0.000000,0.000000,11.194250,16.331716
25,918.030000,50.666000,128.900000,2.527742,117.400000,4.004123,0.000000,0.000000,76.880000,47.030000
26,914.490000,49.892000,163.000000,4.854160,189.600000,6.733189,0.000000,0.000000,92.100000,90.990000
27,914.900000,78.620000,203.300000,1.811921,240.000000,2.751436,0.000000,220.000000,47.890000,43.900000
28,915.840000,40.118000,171.900000,10.535987,188.000000,12.929513,0.000000,0.000000,86.430000,84.390000
29,916.310000,45.428000,183.100000,8.343786,194.600000,10.088599,0.000000,0.000000,86.150000,90.580000
30,919.350000,91.112000,96.400000,2.527742,96.300000,3.377779,0.000000,0.000000,25.620000,35.690000
...,...,...,...,...,...,...,...,...,...,...
996,920.020000,71.114000,92.700000,3.400149,66.600000,4.831790,0.000000,0.000000,48.220000,42.530000
997,921.862507,61.406687,75.152497,2.550632,62.951881,3.070346,0.000000,0.000000,21.630270,23.781313
999,916.860000,79.322000,96.200000,1.767183,134.700000,2.572481,0.000000,0.000000,38.770000,39.430000
1000,919.310310,76.064099,273.110133,2.081832,206.154491,2.688532,0.017665,23.553587,20.316955,23.524625
1001,922.355359,59.819453,53.396700,14.192816,70.522841,18.022470,0.000000,0.000000,19.413096,16.499317
1002,919.710000,43.682000,210.300000,5.010746,225.400000,6.576604,0.010000,200.000000,82.150000,60.980000
1003,918.660000,57.272000,286.300000,3.937014,312.200000,5.480503,0.000000,0.000000,46.560000,43.990000
1004,923.521296,71.574429,40.154379,4.729387,64.917514,6.516347,0.000000,0.000000,16.248784,15.672979
1005,919.460000,71.816000,56.700000,8.813544,74.600000,11.162331,0.000000,0.000000,10.400000,16.430000
1006,915.644139,82.334920,117.954762,1.563611,135.193535,2.399074,0.000000,0.000000,19.833903,22.354166
1007,920.396217,72.220443,226.992920,3.077607,249.101918,4.066265,0.018968,142.256672,30.436398,21.054720
1008,916.660000,56.336000,179.800000,3.579104,203.200000,4.272555,0.000000,0.000000,77.480000,49.090000
1009,910.450000,47.822000,171.900000,14.428263,188.700000,18.074475,0.010000,75.000000,91.790000,91.640000
1010,923.020000,60.494000,274.700000,1.923768,233.300000,2.438265,0.000000,0.000000,7.810000,23.030000
1011,916.840000,55.274000,51.700000,4.943637,71.900000,6.241063,0.010000,110.000000,20.920000,31.620000
1012,923.953387,60.147933,53.810421,18.698476,71.077355,23.377962,0.000000,11.217434,12.615025,13.432440
1013,913.650000,65.678000,166.100000,8.880652,182.000000,11.967629,0.000000,0.000000,42.440000,62.940000
1014,919.760000,64.814000,214.000000,4.294925,232.100000,6.129216,0.000000,0.000000,31.490000,62.490000
1015,919.400000,79.178000,150.100000,2.415895,180.700000,3.579104,0.000000,0.000000,35.400000,48.770000
1016,922.692858,62.727070,60.405585,7.659791,76.347135,9.662590,0.000000,0.000000,25.048508,20.440036
1017,924.790000,68.306000,56.500000,14.987498,77.000000,19.617964,0.000000,0.000000,10.970000,9.320000
1018,919.970000,64.184000,185.500000,0.738190,215.200000,1.319795,0.010000,10.000000,32.700000,44.240000
1019,922.273264,68.789168,57.187508,9.583844,82.330642,12.772295,0.000000,0.000000,7.522057,7.302181
1020,918.700000,74.444000,181.000000,0.917145,127.600000,1.342164,0.000000,0.000000,12.720000,15.130000
1021,919.242813,61.449722,259.308971,1.818528,256.218519,2.363093,0.000000,0.000000,16.379241,21.598433
1022,918.800000,49.874000,52.000000,3.869906,61.200000,4.563358,0.000000,0.000000,40.260000,48.910000
1023,915.200000,59.972000,168.000000,1.990877,186.200000,2.460634,0.000000,0.000000,35.920000,46.690000
1024,919.517597,75.628949,120.844044,2.124286,121.618577,2.794904,0.000000,0.000000,14.133289,12.036096
1025,919.400000,58.406000,40.400000,6.688451,61.600000,8.410894,0.000000,0.000000,15.020000,11.800000
1026,916.540000,80.384000,99.300000,1.096101,96.800000,1.476380,0.000000,0.000000,13.220000,17.510000

In [19]:
data.count() # there is null values

number                    1095
air_pressure_9am          1092
air_temp_9am              1090
avg_wind_direction_9am    1091
avg_wind_speed_9am        1092
max_wind_direction_9am    1092
max_wind_speed_9am        1091
rain_accumulation_9am     1089
rain_duration_9am         1092
relative_humidity_9am     1095
relative_humidity_3pm     1095
dtype: int64

In [20]:
data[data.isnull().any(axis=1)]

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
16,16,917.890000,NaN,169.200000,2.192201,196.800000,2.930391,0.000,0.000000,48.990000,51.190000
111,111,915.290000,58.820000,182.600000,15.613841,189.000000,NaN,0.000,0.000000,21.500000,29.690000
177,177,915.900000,NaN,183.300000,4.719943,189.900000,5.346287,0.000,0.000000,29.260000,46.500000
262,262,923.596607,58.380598,47.737753,10.636273,67.145843,13.671423,0.000,NaN,17.990876,16.461685
277,277,920.480000,62.600000,194.400000,2.751436,NaN,3.869906,0.000,0.000000,52.580000,54.030000
334,334,916.230000,75.740000,149.100000,2.751436,187.500000,4.183078,NaN,1480.000000,31.880000,32.900000
358,358,917.440000,58.514000,55.100000,10.021491,NaN,12.705819,0.000,0.000000,13.880000,25.930000
361,361,920.444946,65.801845,49.823346,21.520177,61.886944,25.549112,NaN,40.364018,12.278715,7.618649
381,381,918.480000,66.542000,90.900000,3.467257,89.400000,4.406772,NaN,0.000000,20.640000,14.350000
409,409,NaN,67.853833,65.880616,4.328594,78.570923,5.216734,0.000,0.000000,18.487385,20.356594
517,517,920.570000,53.600000,100.100000,4.697574,NaN,6.285801,4.712,14842.000000,79.880000,84.530000
519,519,916.250000,55.670000,176.400000,6.666081,188.200000,NaN,0.000,0.000000,72.550000,74.390000
546,546,NaN,42.746000,251.100000,12.929513,274.400000,17.604718,14.627,7825.000000,87.870000,70.770000
620,620,921.200000,56.786000,192.300000,9.551734,201.400000,11.005745,NaN,0.000000,59.790000,77.750000
625,625,912.400000,50.774000,171.600000,NaN,181.400000,4.831790,0.000,0.000000,86.840000,64.740000
656,656,920.830000,66.344000,NaN,15.457255,189.400000,16.486248,0.000,0.000000,23.770000,51.630000
670,670,910.920000,48.362000,156.500000,NaN,177.500000,16.128337,4.970,10560.000000,80.560000,88.220000
672,672,922.448945,72.863773,NaN,3.682370,214.196160,4.849450,0.000,0.000000,16.753670,17.804720
705,705,911.900000,59.072000,199.800000,1.275056,239.500000,1.834291,NaN,0.000000,77.630000,59.130000
731,731,922.970166,51.391847,33.810942,NaN,59.290089,11.111555,0.000,4.735034,34.807753,18.418179
737,737,917.895130,76.804690,104.771020,1.632705,97.178763,NaN,0.000,0.000000,13.771311,16.792455
788,788,917.923442,73.249717,42.101739,4.132698,64.284969,5.345258,0.000,NaN,6.939692,18.793825
840,840,918.043767,NaN,181.774042,0.964376,185.618601,1.570007,0.000,0.000000,11.911222,18.154358
848,848,915.250000,37.562000,246.500000,11.587349,258.700000,NaN,3.171,2891.000000,91.000000,90.780000
861,861,919.065408,NaN,172.303728,2.639600,193.058141,3.326949,0.000,0.000000,12.497839,13.438518
869,869,NaN,45.104000,259.000000,3.265932,275.000000,4.026492,0.000,80.000000,85.270000,90.260000
998,998,914.140000,71.240000,NaN,1.722444,232.900000,2.326418,0.000,0.000000,24.200000,41.380000
1031,1031,922.669195,NaN,47.946284,7.969686,65.770066,10.262337,0.000,0.000000,18.920805,19.641841
1035,1035,919.670000,77.576000,171.800000,6.554234,191.000000,8.164831,0.000,NaN,56.860000,50.650000
1063,1063,917.300185,65.790001,NaN,1.879553,222.498226,2.692862,0.000,0.000000,14.972668,20.966267
1066,1066,919.564869,73.726732,68.704694,3.551777,102.571616,4.861315,NaN,0.000000,11.657314,17.331823

In [24]:
data = data.dropna()
del data['number'] # remove extra column

data.count()

KeyError: 'number'

Now let's drop null values using the *pandas dropna* function.

#### We want this to be a classification
##### So target should be categorical

In [25]:
clean_data = data.copy()
clean_data['high_humidity_label'] = (clean_data['relative_humidity_3pm'] > 24.99)*1
print(clean_data['high_humidity_label'])

0       1
1       0
2       0
3       0
4       1
5       1
6       0
7       1
8       0
9       1
10      1
11      1
12      1
13      1
14      0
15      0
17      0
18      1
19      0
20      0
21      1
22      0
23      1
24      0
25      1
26      1
27      1
28      1
29      1
30      1
       ..
1064    1
1065    1
1067    1
1068    1
1069    1
1070    1
1071    1
1072    0
1073    1
1074    1
1075    0
1076    0
1077    1
1078    0
1079    1
1080    0
1081    0
1082    1
1083    1
1084    1
1085    1
1086    1
1087    1
1088    1
1089    1
1090    1
1091    1
1092    1
1093    1
1094    0
Name: high_humidity_label, Length: 1064, dtype: int32

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Target is stored in 'y'.
<br><br></p>

In [26]:
y=clean_data[['high_humidity_label']].copy()
#y

In [27]:
clean_data['relative_humidity_3pm'].head()

0    36.160000
1    19.426597
2    14.460000
3    12.742547
4    76.740000
Name: relative_humidity_3pm, dtype: float64

In [ ]:
y.head()

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Use 9am Sensor Signals as Features to Predict Humidity at 3pm
<br><br></p>

In [28]:
morning_features = ['air_pressure_9am','air_temp_9am','avg_wind_direction_9am','avg_wind_speed_9am',
        'max_wind_direction_9am','max_wind_speed_9am','rain_accumulation_9am',
        'rain_duration_9am']

In [29]:
X = clean_data[morning_features].copy()

In [30]:
X.columns

Index(['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am'],
      dtype='object')

In [31]:
y.columns

Index(['high_humidity_label'], dtype='object')

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Perform Test and Train split

<br><br></p>

## REMINDER: Training Phase

In the **training phase**, the learning algorithm uses the training data to adjust the model’s parameters to minimize errors.  At the end of the training phase, you get the trained model.

<img src="TrainingVSTesting.jpg" align="middle" style="width:550px;height:360px;"/>

<BR>
In the **testing phase**, the trained model is applied to test data.  Test data is separate from the training data, and is previously unseen by the model.  The model is then evaluated on how it performs on the test data.  The goal in building a classifier model is to have the model perform well on training as well as test data.

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
#type(X_train)
#type(X_test)
#type(y_train)
#type(y_test)
#X_train.head()
#y_train.describe()

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Fit on Train Set
<br><br></p>

In [33]:
model = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=10,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [34]:
type(model)

sklearn.tree.tree.DecisionTreeClassifier

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Predict on Test Set 

<br><br></p>

In [35]:
pred = model.predict(X_test)

In [36]:
pred[:10]

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0])

In [39]:
classification_report(y_test)

'              precision    recall  f1-score   support\n\n           0       0.58      0.85      0.69        79\n           1       0.88      0.64      0.74       134\n\n    accuracy                           0.72       213\n   macro avg       0.73      0.74      0.72       213\nweighted avg       0.77      0.72      0.72       213\n'

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Measure Accuracy of the Classifier
<br><br></p>

In [41]:
accuracy_score(y_true = y_test, y_pred = pred)

0.7183098591549296

# Example 2

We will again be using the open dataset from the popular site <a href="https://www.kaggle.com">Kaggle</a> that we used in Week 1 for our example. 

Recall that this <a href="https://www.kaggle.com/hugomathien/soccer">European Soccer Database</a> has more than 25,000 matches and more than 10,000 players for European professional soccer seasons from 2008 to 2016. 

**Note:** Please download the file *database.sqlite* if you don't yet have it in your *Week-7-MachineLearning* folder.

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Import Libraries<br><br></p>

In [ ]:
import sqlite3
import pandas as pd 
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Read Data from the Database into pandas
<br><br></p>

In [ ]:
# Create your connection.
cnx = sqlite3.connect('database.sqlite')
df = pd.read_sql_query("SELECT * FROM Player_Attributes", cnx)

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.columns

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Declare the Columns You Want to Use as Features
<br><br></p>

In [ ]:
features = [
       'potential', 'crossing', 'finishing', 'heading_accuracy',
       'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy',
       'long_passing', 'ball_control', 'acceleration', 'sprint_speed',
       'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina',
       'strength', 'long_shots', 'aggression', 'interceptions', 'positioning',
       'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle',
       'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning',
       'gk_reflexes']

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Specify the Prediction Target
<br><br></p>

In [ ]:
target = ['overall_rating']

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Clean the Data<br><br></p>

In [ ]:
df = df.dropna()

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Extract Features and Target ('overall_rating') Values into Separate Dataframes
<br><br></p>

In [ ]:
X = df[features]

In [ ]:
y = df[target]

Let us look at a typical row from our features:

In [ ]:
X.iloc[2]

Let us also display our target values:

In [ ]:
y

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Split the Dataset into Training and Test Datasets
<br><br></p>

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=324)

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

(1) Linear Regression: Fit a model to the training set
<br><br></p>

In [ ]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Perform Prediction using Linear Regression Model
<br><br></p>

In [ ]:
y_prediction = regressor.predict(X_test)
y_prediction

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

What is the mean of the expected target value in test set ?
<br><br></p>

In [ ]:
y_test.describe()

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Evaluate Linear Regression Accuracy using Root Mean Square Error

<br><br></p>

In [ ]:
RMSE = sqrt(mean_squared_error(y_true = y_test, y_pred = y_prediction))

In [ ]:
print(RMSE)

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

(2) Decision Tree Regressor: Fit a new regression model to the training set
<br><br></p>

In [ ]:
regressor = DecisionTreeRegressor(max_depth=20)
regressor.fit(X_train, y_train)

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Perform Prediction using Decision Tree Regressor
<br><br></p>

In [ ]:
y_prediction = regressor.predict(X_test)
y_prediction

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

For comparision: What is the mean of the expected target value in test set ?
<br><br></p>

In [ ]:
y_test.describe()

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Evaluate Decision Tree Regression Accuracy using Root Mean Square Error

<br><br></p>

In [ ]:
RMSE = sqrt(mean_squared_error(y_true = y_test, y_pred = y_prediction))

In [ ]:
print(RMSE)